name : first push on git
on : 
  push : 
    branches : ["master"]
jobs :
  test :
    runs-on : windows-latest
    steps: 
      uses : actions/chekoutV3
      uses : actions/setup-javaV3
        with :
          java-version : "11"
          cache : "maven"
          distribution : "temurin"
      uses :  browser-actions/setup-chrome@latest
      run : mvn clean test
      

